/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { USDC } from "./USDC";
export * as factories from "./factories";
export { USDC__factory } from "./factories/USDC__factory";
